services:
  database:
    image: postgres:18-alpine
    container_name: school_portal_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: school_portal_backend
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      DB_URL: jdbc:postgresql://database:5432/${POSTGRES_DB}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_WEB_CORS_ALLOWED_ORIGINS: ${FRONTEND_URL}

  frontend:
    build: ./frontend
    container_name: school_portal_frontend
    ports:
      - "4321:4321"
    depends_on:
      - backend
    environment:
      PUBLIC_API_URL: ${BACKEND_URL}

volumes:
  db_data: